name: Testes Back-End

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - working-directory: backend/auth-service
        run: npm install
      - working-directory: backend/app-service
        run: npm install
      - working-directory: backend/auth-service
        run: npm test --if-present
      - working-directory: backend/app-service
        run: npm test --if-present
